### ISSUE TITLE
As an user, I want to search specific libraries so it satisfies my needs.

### ISSUE THREAD

**Issue by FranckyXue** [gcivil-nyu-org/INET-Monday-Fall2023-Team-1#53]

**Comment by FranckyXue** [comment]
User story
As an user, I want to search specific libraries so it satisfies my needs.
Acceptance criteria
Keep track the libraries and book clubs' details such as schedule and location.
Definition of Done
Able to view libraries and their details without having an account

**Comment by kolharsam** [comment]
@FranckyXue This is in the incorrect repository. Please create yours in the right directory.
