### ISSUE TITLE
Bug in Login Page Error Messages

### ISSUE THREAD

**Issue by agoluoglu** [gcivil-nyu-org/INET-Monday-Fall2023-Team-1#84]
When I try to login with an invalid email address AND a password that is too short, only the error message for the short password appears.
Also, the document says that an error message should appear if I login incorrectly. However, the error message that appears in the top right is inside an array of code-like style, rather than directly displayed. I have attached an image example of how I have to click arrows to expand the information to get to the error message, and how only one error message appears even though both fields are invalid.
<img width="1148" alt="Screenshot 2023-11-17 at 5 49 32 PM" src="https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-1/assets/119933910/68f32b72-000a-43db-becd-091480d13cc8">

**Comment by ManaliTanna** [comment]
Marking as duplicates, please see issue #80
