### ISSUE TITLE
Scenario 1: Registration Process

### ISSUE THREAD

**Issue by utsavoza** [gcivil-nyu-org/INET-Monday-Fall2023-Team-1#94]
### Steps to reproduce:
1. Navigate to https://ui.furbabyapi.net/signup
2. Submit the form according to the following parameters:
    - Email Address: ugo1@nyu.edu
    - Password: CommonPassword@!23
    - User Type Preference: Select Pet Sitter AND Pet Owner

### Actual Behavior

An error shown with message "Failed to create an account"

![Screenshot 2023-11-19 at 4 48 42 AM](https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-1/assets/13735475/a8c99d04-64f8-452c-9a33-571782a37e26)

### Expected Behavior

Upon successful registration, user should be redirected to the login page.

**Comment by ManaliTanna** [comment]
This issue will be fixed when we fix our migrations. Thank you!
