### ISSUE TITLE
Cannot either login or signup

### ISSUE THREAD

**Issue by SoyMark** [gcivil-nyu-org/INET-Monday-Fall2023-Team-1#95]
I tried serveral accounts(test1, test2, ta_test) provided in the document, but none of them worked. 
My attempt to sign up also failed. I followed the error message(which, I think, can be better displayed instead of displaying a json data) to edit my password, but in the end the problem seems to be related to profile picture. 
<img width="402" alt="team1_1" src="https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-1/assets/65658776/33671fdb-25df-4b7d-9253-479fc369b39c">
<img width="428" alt="team1_2" src="https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-1/assets/65658776/5004adc5-9b67-4493-bbf5-c2800c7945fc">

**Comment by ManaliTanna** [comment]
This issue will be fixed when we fix our migrations. Thank you!
